cloud:
  aws:
    credentials:
      access-key: AKIAXJI5U7SDL4MYZ244
      secret-key: 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

  stack:
    auto: false

  application:
    bucket:
      name: bitsbids

  server:
    port: 8080
